const Data = [
    {
        id: 1,
        image:"BlogImages/pexels-moose-photos-1037993.jpg",
        img_tag:"Designing",
        heading:"Top Graphic Design Resources",
        date:"January 9, 2023",
        paragrapgh:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut...",
    },
    {
        id: 2,
        image:"BlogImages/pexels-picjumbocom-196644.jpg",
        img_tag:"Designing",
        heading:"Top Web Design Topic",
        date:"January 9, 2023",
        paragrapgh:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut...",
    },
    {
        id: 3,
        image:"BlogImages/laptop-gbedf0e9f9_1280.jpg",
        img_tag:"Frontend",
        heading:"CSS3 Background Animation",
        date:"January 15, 2023",
        paragrapgh:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut...",
    },
    {
        id: 4,
        image:"BlogImages/pexels-cottonbro-studio-4709289.jpg",
        img_tag:"Frontend",
        heading:"Smooth Scrolling In Web Development",
        date:"January 9, 2023",
        paragrapgh:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut...",
    },
    {
        id: 5,
        image:"BlogImages/pexels-olia-danilevich-4974912.jpg",
        img_tag:"Backend",
        heading:"How To Develop Backend Logic",
        date:"January 9, 2023",
        paragrapgh:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut...",
    },
    {
        id: 6,
        image:"BlogImages/digital-marketing-gcef55a09c_1280.jpg",
        img_tag:"Seo",
        heading:"How To Rank Your Personal Website",
        date:"January 9, 2023",
        paragrapgh:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut...",
    },
]
export default Data